import os
import sys
import 
os.system("clear")
os.system("apt install figlet")
os.system("figlet Bruteforce")
a = input("id/email>>")
a = input("pasword>>")
os.system("clear")
print ("hacking starting...10 ")
os.system("sleep 3")
print ("hacking starting...20 ")
os.system("sleep 3")
print ("hacking starting...30 ")
os.system("sleep 3")
print ("hacking starting...40 ")
os.system("sleep 3")
print ("hacking starting...50 ")
os.system("sleep 3")
print ("hacking starting...80 ")
print ("hacking starting...90 ")
print ("Hack Done... ")
os.system("sleep 3")
print ("===================")
print ("!password>>minmaylol!")
print ("!===================")

